---
title: "7BUIS008W Data Mining & Machine Learning - Coursework 2"
author: "Andrew Keats"
date: "8th January 2017"
output:
  customOutput::html5:
    css: 
      - ~/work/study/msc-idc/dmml/cw2/assets/css/modest.css
      - ~/work/study/msc-idc/dmml/cw2/assets/css/custom.css
    fig_caption: yes
    keep_md: yes
    toc: yes
    toc_depth: 2
    template: ~/work/study/msc-idc/dmml/cw2/templates/html5.html
  html_document:
    css:
    - ~/work/study/msc-idc/dmml/cw2/assets/css/modest.css
    - ~/work/study/msc-idc/dmml/cw2/assets/css/custom.css
    fig_caption: yes
    keep_md: yes
    toc: yes
    toc_depth: 2
chapters: yes
fontsize: 12pt
css: null
papersize: A4
abstract: Show evidence of understanding of the clustering and modelling concepts, through the implementation of requested algorithms using real datasets. Implementation is performed in R environment, while students need to perform some critical evaluation of their results.
toc-depth: 2
toc-title: Table of Contents
bibliography: bibliography.ris
csl: ../build/harvard-university-of-westminster.csl
nocite: | 
  @doc:5a52e013e4b02942103f7fc1, @doc:5a52de2be4b01d3dd55666a1, @doc:5a52ddf0e4b0e3e5a63645e4, @doc:5a52ddd8e4b02942103f7f9c, @doc:5a52dd8ce4b0eeb35a4a1e8c, @doc:5a52dd7be4b08e15c00cdc97, @doc:5a52dc89e4b02942103f7f82, @doc:5a52dc77e4b02942103f7f81, @doc:5a52ca43e4b02942103f7d57, @doc:5a52c93ce4b02942103f7d43, @doc:5a5192fbe4b02942103f2d47, @doc:5a4f0c37e4b09d5cea02c23b, @doc:5a4edbf5e4b0ac315a55bfc7, @doc:5a4ec6f3e4b020410252c182, @doc:5a4ec56ae4b0062b162abbf0, @doc:5a4ec538e4b0ac315a55beae, @doc:5a4eba0ee4b020410252c08d, @doc:5a4e5a3ae4b09d5cea02a9a9, @doc:5a4db356e4b0ac315a5583fc, @doc:5a4db301e4b0c2a8b20cd934, @doc:5a4db27ee4b0c2a8b20cd927, @doc:5a4da870e4b0c2a8b20cd807, @doc:5a4c434ae4b0204102524624, @doc:5a4c3ba6e4b0ac315a552aac, @doc:5a4c3b69e4b0ac315a552aa8, @doc:5a4c395ce4b0c2a8b20c9406, @doc:5a4c2612e4b01d3b9773f835, @doc:5a4c1f06e4b0c2a8b20c917c, @doc:5a4bd8d3e4b09d5cea022500, @doc:5a4bd7bbe4b0062b162a30a0, @doc:5a4b8c54e4b09d5cea020a62, @doc:5a4b8c05e4b0c2a8b20c5456, @doc:5a4b82e4e4b0062b162a126c, @doc:5a458a17e4b022cc4f774122, @doc:5a458724e4b000cfec287c20, @doc:5a4582c4e4b02eb8a444a227, @doc:5a458258e4b022cc4f773fdd, @doc:5a457f22e4b022cc4f773f51, @doc:5a457cf1e4b06a7ca331608d
---

```{r setup, include=FALSE, message=FALSE}
#knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
knitr::opts_chunk$set(echo = TRUE)
set.seed(4321)
```


```{r q1, child = 'q1.rmd'}
```

<!--```{r q2, child = 'q2.rmd'}
```-->

<!--```{r q3, child = 'q3.rmd'}
```-->

<!--```{r q4, child = 'q4.rmd'}
```-->

<!--```{r q5, child = 'q5.rmd'}
```-->

<!--```{r q6, child = 'q6.rmd'}
```-->


<section>

# References

<div id="refs"></div>

</section>