---
title: "q1"
output: html_document
bibliography: bibliography.ris
---


```{r setup-t3, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
set.seed(4321)
```


```{r deps-t3, echo=FALSE, include=FALSE, message=FALSE}
if(!require(rJava)) install.packages('rJava')
if(!require(caret)) install.packages("caret", repos = mirrorUrl)
if(!require(RWeka)) install.packages("RWeka", repos = mirrorUrl)
#e1071
if(!require(e1071)) install.packages("e1071", repos = mirrorUrl)
#libcoin
if(!require(coin)) install.packages("coin", repos = mirrorUrl)
#partykit
if(!require(partykit)) install.packages("partykit", repos = mirrorUrl)
#rpart
if(!require(rpart.plot)) install.packages("rpart.plot", repos = mirrorUrl)
#
library("e1071")
library("caret")
library("RWeka")
library("rpart.plot")
library("libcoin")
library("partykit")
```

<section>

#Task 3: Build Train and Test a Decision Tree type Classifier

##Premise

>You need to construct, train and test Decision Tree type classifier (C4.5, Random Forest) in R. Train and test your decision tree classifier using the training and test sets generated based on the methods tried as part of the 2nd Task.

<!--
• Building of Decision Tree type classifier (C4.5, Random Forest) in R 8
• Training of Decision Tree type classifier (C4.5, Random Forest) in R 8
• Testing of Decision Tree type classifier (C4.5, Random Forest) 9
-->

##C4.5 Decision Tree

```{r dt-c4_5-h}
#method = 'J48'
#as.factor(
#dt.c4_5_h <- J48(rings~., holdout.training) 
#dt.c4_5_h <- J48(as.factor(rings)~., holdout.training) 
#dt.c4_5_h2 <- train(as.factor(rings) ~., method="J48", holdout.training, tuneLength = 8)
#dt.c4_5_h <- train(rings ~., method="J48", data=holdout.training, tuneLength = 8)

#dt.c4_5_h
#dt.c4_5_h2$finalModel
```

```{r dt-plots}
#plot(dt.c4_5_h$finalModel, box.palette = "Reds", tweak = 1.2)
```

```{r dt-test}
#set.seed(1958)  # set a seed to get replicable results
#train <- createFolds(iris$Species, k=10)
#C45Fit <- train(Species ~., method="J48", data=iris,
#                tuneLength = 5,
#                trControl = trainControl(
#                  method="cv", indexOut=train))
```

</section>
